# Generated by Django 4.2.3 on 2023-08-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plantType', models.CharField(max_length=100)),
                ('bloom', models.TextField(max_length=250)),
                ('height', models.CharField(max_length=100)),
                ('spacing', models.CharField(max_length=100)),
                ('hardiness', models.CharField(max_length=100)),
                ('pinch', models.CharField(max_length=100)),
                ('deerResistant', models.BooleanField()),
                ('image', models.TextField(max_length=1000)),
            ],
        ),
    ]
