# Generated by Django 4.2.3 on 2023-08-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_watering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watering',
            old_name='cat',
            new_name='flower',
        ),
    ]
