# Generated by Django 4.2.3 on 2023-08-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_garden_alter_watering_options_alter_watering_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='deerResistant',
            field=models.BooleanField(default=False),
        ),
    ]
