# Generated by Django 4.2.3 on 2023-08-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_flower_deerresistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='gardens',
            field=models.ManyToManyField(to='main_app.garden'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='deerResistant',
            field=models.BooleanField(),
        ),
    ]
