# Generated by Django 4.2.3 on 2023-08-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_flower_gardens_alter_flower_deerresistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='deerResistant',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='Deer Resistant'),
        ),
    ]
